### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NoxiousPluK** [Jjagg/SharpVR#1]
Hi!

I'd love to refresh this a bit and play around with it, but it doesn't seem to have a license currently.
Would you mind assigning one to the project?

If you have trouble picking and/or want to release it to the public domain, I suggest using the unlicense (unlicense.org).

Thanks in advance!

**Comment by Jjagg** [comment]
Hey! I added the Unlicense as you suggested :)

Feel free to use this however!
